# Generated by Django 4.0.4 on 2022-05-27 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eleve',
        ),
        migrations.DeleteModel(
            name='Enseignants',
        ),
        migrations.DeleteModel(
            name='Etudiant',
        ),
        migrations.DeleteModel(
            name='Examens',
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.DeleteModel(
            name='Ressouces',
        ),
        migrations.DeleteModel(
            name='Ue',
        ),
    ]
